export const DESTINATIONS = ["Dhaka", "Chittagong", "Sylhet", "Rajshahi"];
export const TIMES = ["8:00 AM", "9:00 AM", "5:00 PM", "6:00 PM"];

//default buses, routes and time
export const DEFAULT_BUSES = [
  {
    id: 1,
    name: "Express Line 1",
    routes: ["Dhaka", "Chittagong"].join(", "),
    times: ["8:00 AM", "5:00 PM"].join(", "),
    seats: [
      { number: "A1", booked: false, details: null, position: "window" },
      { number: "A2", booked: false, details: null, position: "aisle" },
      { number: "A3", booked: false, details: null, position: "center" },
      { number: "B1", booked: false, details: null, position: "window" },
      { number: "B2", booked: false, details: null, position: "aisle" },
      { number: "B3", booked: false, details: null, position: "center" },
      { number: "C1", booked: false, details: null, position: "window" },
      { number: "C2", booked: false, details: null, position: "aisle" },
      { number: "C3", booked: false, details: null, position: "center" },
      { number: "D1", booked: false, details: null, position: "window" },
      { number: "D2", booked: false, details: null, position: "aisle" },
      { number: "D3", booked: false, details: null, position: "center" },
      { number: "E1", booked: false, details: null, position: "window" },
      { number: "E2", booked: false, details: null, position: "aisle" },
      { number: "E3", booked: false, details: null, position: "center" },
    ],
  },
  {
    id: 2,
    name: "Express Line 2",
    routes: ["Sylhet", "Rajshahi"].join(", "),
    times: ["9:00 AM", "6:00 PM"].join(", "),
    seats: [
      { number: "A1", booked: false, details: null, position: "window" },
      { number: "A2", booked: false, details: null, position: "aisle" },
      { number: "A3", booked: false, details: null, position: "center" },
      { number: "B1", booked: false, details: null, position: "window" },
      { number: "B2", booked: false, details: null, position: "aisle" },
      { number: "B3", booked: false, details: null, position: "center" },
      { number: "C1", booked: false, details: null, position: "window" },
      { number: "C2", booked: false, details: null, position: "aisle" },
      { number: "C3", booked: false, details: null, position: "center" },
      { number: "D1", booked: false, details: null, position: "window" },
      { number: "D2", booked: false, details: null, position: "aisle" },
      { number: "D3", booked: false, details: null, position: "center" },
      { number: "E1", booked: false, details: null, position: "window" },
      { number: "E2", booked: false, details: null, position: "aisle" },
      { number: "E3", booked: false, details: null, position: "center" },
    ],
  },
  {
    id: 3,
    name: "Express Line 3",
    routes: ["Dhaka", "Sylhet"].join(", "),
    times: ["8:00 AM", "6:00 PM"].join(", "),
    seats: [
      { number: "A1", booked: false, details: null, position: "window" },
      { number: "A2", booked: false, details: null, position: "aisle" },
      { number: "A3", booked: false, details: null, position: "center" },
      { number: "B1", booked: false, details: null, position: "window" },
      { number: "B2", booked: false, details: null, position: "aisle" },
      { number: "B3", booked: false, details: null, position: "center" },
      { number: "C1", booked: false, details: null, position: "window" },
      { number: "C2", booked: false, details: null, position: "aisle" },
      { number: "C3", booked: false, details: null, position: "center" },
      { number: "D1", booked: false, details: null, position: "window" },
      { number: "D2", booked: false, details: null, position: "aisle" },
      { number: "D3", booked: false, details: null, position: "center" },
      { number: "E1", booked: false, details: null, position: "window" },
      { number: "E2", booked: false, details: null, position: "aisle" },
      { number: "E3", booked: false, details: null, position: "center" },
    ],
  },
  {
    id: 4,
    name: "Express Line 4",
    routes: ["Chittagong", "Rajshahi"].join(", "),
    times: ["9:00 AM", "5:00 PM"].join(", "),
    seats: [
      { number: "A1", booked: false, details: null, position: "window" },
      { number: "A2", booked: false, details: null, position: "aisle" },
      { number: "A3", booked: false, details: null, position: "center" },
      { number: "B1", booked: false, details: null, position: "window" },
      { number: "B2", booked: false, details: null, position: "aisle" },
      { number: "B3", booked: false, details: null, position: "center" },
      { number: "C1", booked: false, details: null, position: "window" },
      { number: "C2", booked: false, details: null, position: "aisle" },
      { number: "C3", booked: false, details: null, position: "center" },
      { number: "D1", booked: false, details: null, position: "window" },
      { number: "D2", booked: false, details: null, position: "aisle" },
      { number: "D3", booked: false, details: null, position: "center" },
      { number: "E1", booked: false, details: null, position: "window" },
      { number: "E2", booked: false, details: null, position: "aisle" },
      { number: "E3", booked: false, details: null, position: "center" },
    ],
  },
];
